#!/bin/bash

######################################################################
#
# scripts/node_config -- Configure a Eucalyptus node node
#
######################################################################

# clear existing config
rm -rf $EUCALYPTUS/var/lib/eucalyptus/db

# apply the configuration
$EUCALYPTUS/usr/sbin/euca_conf --setup

euca_conf --initialize

