#!/bin/bash
#
# scripts/stop_secondary
#	Stop a running secondary head node
#

source util.sh

main() {
	parse_args
	deregister_eucalyptus_components
	deregister_secondary
	stop_secondary
}

#####################################################################
# De-register Eucalyptus components
# Globals:
#	CC_PART
#	NODENAME
#	PUBLIC_IP
# Arguments:
#	none
# Returns:
#	none
######################################################################

deregister_eucalyptus_components() {
	pdebug "Deregistering SC"
	euca_conf --deregister-sc -P $CC_PART -H "$PUBLIC_IP" -C "sc-$NODENAME"
	pdebug "Deregistering CC"
	euca_conf --deregister-cluster -P $CC_PART -H "$PUBLIC_IP" -C "cc-$NODENAME"
	pdebug "Deregistering Services"
	euca_conf --deregister-service -T user-api -H "$PUBLIC_IP" -N "api-$NODENAME"
}

######################################################################
# De-register component from head nodes
# Globals:
#	NODENAME
#	PRIMARY_HEAD
# Arguments:
#	none
# Returns:
#	none
######################################################################

deregister_secondary() {
	pdebug "Deregistering Secondary CLC"
	ssh "$PRIMARY_HEAD"<<EOF
euca_conf --deregister-cloud -P eucalyptus -H "$PUBLIC_IP" --C "clc-$NODENAME"
EOF
}

######################################################################
# Stop Eucalyptus services
# Globals:
#	none
# Arguments:
#	none
# Returns:
#	none
######################################################################

stop_secondary_head() {
	pdebug "Stopping Secondary CLC"
	service eucalyptus-cloud stop
	pdebug "Stopping CC"
	service eucalyptus-cc stop
}

main
