#!/bin/bash
#
# scripts/stop_node_controller
#	Stop and de-register a new node controller
#

source util.sh

main() {
	parse_args $@
	if [[ -z "$PRIMARY_HEAD" || -z "$SECONDARY_HEAD" ]]; then
		echo "Usage: -p <primary> -q <secondary>"
		exit 1
	fi
	stop_node_controller
	deregister_node_controller
}

######################################################################
# Stop node controller
# Globals:
#	none
# Arguments:
#	none
# Returns:
#	none
######################################################################

stop_node_controller() {
	pdebug "Stopping node controller"
	service eucalyptus-nc start
}

######################################################################
# De-register node controller from head nodes
# Globals:
#	PRIMARY_HEAD
#	PRIVATE_IP
#	SECONDARY_HEAD
# Arguments:
#	none
# Returns:
#	none
######################################################################

deregister_node_controller() {
	pdebug "Deregistering node controller from primary head ($PRIMARY_HEAD)"
	ssh "$PRIMARY_HEAD"<<EOF
euca_conf --deregister-nodes "$PRIVATE_IP"
EOF

	if [[ -n $SECONDARY_HEAD ]]; then
		pdebug "Deregistering node controller from secondary head ($SECONDARY_HEAD)"
		ssh "$SECONDARY_HEAD"<<EOF
euca_conf --deregister-nodes "$PRIVATE_IP"
EOF
	fi
}

main $@
