#!/bin/bash

######################################################################
#
# scripts/head_config -- Configure a Eucalyptus head node
#
######################################################################

# Apply the configuration
$EUCALYPTUS/usr/sbin/euca_conf --setup

# Set max semaphores available to Postgres
echo "250 32000 32 1536" > /proc/sys/kernel/sem

euca_conf --initialize

