#!/bin/bash
#
# scripts/start_node
#	Start and register a new node controller
#

source util.sh

main() {
	parse_args $@
	if [[ -z "$PRIMARY_HEAD" ]]; then
		echo "Usage: -p <primary> [-q <secondary>]"
		exit 1
	fi
	start_node_controller
	register_node_controller
}

######################################################################
# Start node controller
# Globals:
#	none
# Arguments:
#	none
# Returns:
#	none
######################################################################

start_node_controller() {
	pdebug "Starting node controller"
	service eucalyptus-nc start
}

######################################################################
# Register node controller with head nodes
# Globals:
#	PRIMARY_HEAD
#	PRIVATE_IP
#	SECONDARY_HEAD
# Arguments:
#	none
# Returns:
#	none
######################################################################

register_node_controller() {
	pdebug "Registering node controller on primary head ($PRIMARY_HEAD)"
	ssh "$PRIMARY_HEAD"<<EOF
euca_conf --register-nodes "$PRIVATE_IP"
EOF

	if [[ -n $SECONDARY_HEAD ]]; then
		pdebug "Registering node controller on primary head ($SECONDARY_HEAD)"
		ssh "$SECONDARY_HEAD"<<EOF
euca_conf --register-nodes "$PRIVATE_IP"
EOF
	fi
}

main $@
