#!/bin/bash
#
# Simluate start nc
#

while getopts ":h:" opt; do
    case "$opt" in
        h)
            HOST="$OPTARG"
            ;;
        ?)
            ;;
    esac
done

source test/hooks/config.sh

python -m blacknight util start_service_on_host node_controller $HOST
