#!/bin/bash
#
# Simluate stop db
#

while getopts ":i:" opt; do
    case "$opt" in
        h)
            INSTANCE="$OPTARG"
            ;;
        ?)
            ;;
    esac
done

source test/hooks/config.sh

python -m blacknight util stop_service db $INSTANCE
