#!/bin/bash
#
# Simluate start secondary head
#

while getopts ":h:" opt; do
    case "$opt" in
        h)
            HOST="$OPTARG"
            ;;
        ?)
            ;;
    esac
done

source test/sim/hooks/config.sh

python -m blacknight util start_service_on_host secondary_head $HOST
