#!/bin/bash
#
# Simluate stop hadoop
#

while getopts ":i:" opt; do
    case "$opt" in
        h)
            INSTANCE="$OPTARG"
            ;;
        ?)
            ;;
    esac
done

source test/sim/hooks/config.sh

python -m blacknight util stop_service hadoop $INSTANCE
